<a href="https://colab.research.google.com/github/vasanthidharmalingam/python_fdp/blob/main/python_fdp_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_str="vasanthi"
print(my_str[7])
print("A" in my_str)

i
False


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1=np.arange(1)
print(arr1)

[0]


In [ ]:
arr1=np.zeros((3,3))
arr2=np.ones((2,3))
print(arr1)
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr0=np.array([[1,2],[2,3]])
arr1=np.array([1,2,3,4,5])
arr2=np.array([100,200,300,400,500])
arr3=arr1+arr2
print(arr3)
arr4=arr1*arr2
print(arr4)
print(arr0.shape)
print(arr2.size)
print(arr3.dtype)

[101 202 303 404 505]
[ 100  400  900 1600 2500]
(2, 2)
5
int32
